import Main from '@/components/Main';

export const metadata = {
  title: 'KC Auth',
  description: 'Generated by Keshavcodex',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body style={{ margin: 0 }}>
          <Main>{children}</Main>
      </body>
    </html>
  );
}
